spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth2
    name: local-postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    open-in-view: false
