spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/oauth2
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 876862065988-ddrqt7c47e25mk5ju8f30g0qsfn1rokc.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: UEb2pI6CRV_pjnvultOT
            client-secret: go0P90IGJO
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: bf56a9d2ad0d3230fa65bb19d3b8ae41
            client-secret: ShB3B3RAsLb8sdzFnFxgkZlic4FsgFZ4
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

# JWT ??
jwt:
  secretKey: 'DA321J3I1DUSJ3QJEALJKAjdlk2j31kd2J3KD1weqkqk32l133K2123JH123HSU32j31j3qwe'

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh